// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb-hIxpkokFxt_TlAxSfRPPfRo7_IIHEg',
    appId: '1:67606741594:web:fb35ad0403bc880a434e63',
    messagingSenderId: '67606741594',
    projectId: 'wathsapp-8aa84',
    authDomain: 'wathsapp-8aa84.firebaseapp.com',
    storageBucket: 'wathsapp-8aa84.firebasestorage.app',
    measurementId: 'G-WLVZDNCBKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtE2Ugy9-2sg-eMGvthMx2i6R9P9VN6Qw',
    appId: '1:67606741594:android:771ea02f6cadd1d8434e63',
    messagingSenderId: '67606741594',
    projectId: 'wathsapp-8aa84',
    storageBucket: 'wathsapp-8aa84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAx_gVzF1a87ZYunkv1XMXhVULjWIkK4Y',
    appId: '1:67606741594:ios:af193f1ef88e1f06434e63',
    messagingSenderId: '67606741594',
    projectId: 'wathsapp-8aa84',
    storageBucket: 'wathsapp-8aa84.firebasestorage.app',
    iosBundleId: 'com.example.appZapzap',
  );
}
